# Generated by Django 4.0.1 on 2022-01-27 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_tguser_tg_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguser',
            name='tg_hash',
        ),
    ]
